### ISSUE TITLE
Handling trailing slash

### ISSUE THREAD

**Issue by romaintailhurat** [romaintailhurat/pogzops#1]
Consider this YAML command file:

```yaml
ops:
  - type: "copy"
    ids:
      - "lsx8aoze"
    source_env:
      name: "recette"
      url: "https://api-conception-questionnaires-recette.dev.kube.insee.fr"
      token: "mytokenloremipsum"
      cert_path2: "/path/to/cert-chain.pem"
    target_env:
      name: "prod"
      url: "https://api-conception-questionnaires.insee.fr/"
      token: "abcdef"
```

The URL in the `target_env` contains a `/` that will cause the request to be in error.
